package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/ACTIVE.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /jenkins/workspace/8-2-build-macosx-x86_64/jdk8u271/605/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Wednesday, September 16, 2020 4:55:00 PM GMT
*/

public interface ACTIVE
{

  /** Object adapter state that indicates normal request processing.
     */
  public static final short value = (short)(1);
}
